export const posts = [
  {
    id: 1,
    title: 'Post 1',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    img: 'https://placehold.co/200x200/orange/white',
    marked: true,
  },
  {
    id: 2,
    title: 'Post 2',
    text: 'Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.',
    img: 'https://placehold.co/200x200/orange/white',
    marked: false,
  },
  {
    id: 3,
    title: 'Post 3',
    text: 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    img: 'https://placehold.co/200x200/orange/white',
    marked: true,
  },
  {
    id: 4,
    title: 'Post 4',
    text: 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    img: 'https://placehold.co/200x200/orange/white',
    marked: false,
  },
  {
    id: 5,
    title: 'Post 5',
    text: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    img: 'https://placehold.co/200x200/orange/white',
    marked: true,
  },
  {
    id: 6,
    title: 'Post 6',
    text: 'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    img: 'https://placehold.co/200x200/orange/white',
    marked: false,
  },
  {
    id: 7,
    title: 'Post 7',
    text: 'Fusce ut placerat orci nulla pellentesque dignissim enim sit amet venenatis urna cursus eget nunc.',
    img: 'https://placehold.co/200x200/orange/white',
    marked: true,
  },
  {
    id: 8,
    title: 'Post 8',
    text: 'Vestibulum morbi blandit cursus risus at ultrices mi tempus imperdiet nulla malesuada pellentesque elit eget gravida.',
    img: 'https://placehold.co/200x200/orange/white',
    marked: false,
  },
  {
    id: 9,
    title: 'Post 9',
    text: 'Donec massa sapien faucibus et molestie ac feugiat sed lectus vestibulum mattis ullamcorper velit.',
    img: 'https://placehold.co/200x200/orange/white',
    marked: true,
  },
  {
    id: 10,
    title: 'Post 10',
    text: 'Aliquam nulla facilisi cras fermentum odio eu feugiat pretium nibh ipsum consequat.',
    img: 'https://placehold.co/200x200/orange/white',
    marked: false,
  },
]
